disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Elvio Santangelo"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006 January 2"
  logo = "img/DarakAvatar8_circle_64x64.png"
  # secondaryLogo = "img/DarakAvatar8_circle_64x64.png"
  description = "Personal potfolio website"
  copyright = "© 2025 Elvio Santangelo"

[params.author]
  name = "Elvio Santangelo"
  email = "elviost@gmail.com"
  image = "img/DarakElvio-circle.png"
  imageQuality = 96
  headline = "BSc Computer Science <br>Game Developer"
  bio = "Italian Game Dev"
  links = [
    { email = "mailto:elviost@gmail.com" },
    { github = "https://github.com/Darakuu" },
    { linkedin = "https://www.linkedin.com/in/elviosant/" },
    { steam = "https://steamcommunity.com/id/Darakuu/" },
  ]
